#!/bin/bash

source /tmp/hadoop-`echo $USER`/etc/init.d/hadoop.env
source ${HADOOP_HOME}/etc/hadoop/hadoop-env.sh
source ${HADOOP_HOME}/etc/hadoop/yarn-env.sh

RETVAL=0
PIDFILE="${HADOOP_MAPRED_PID_DIR}/mapred-mapred-historyserver.pid"
desc="Hadoop MapReduce History Server daemon"

start() {
  echo -n $"Starting $desc (hadoop-historyserver): "
  ${HADOOP_HOME}/sbin/mr-jobhistory-daemon.sh --config "${HADOOP_CONF_DIR}" start historyserver
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && touch /tmp/hadoop-historyserver.lock
  return $RETVAL
}

stop() {
  echo -n $"Stopping $desc (hadoop-historyserver): "
  ${HADOOP_HOME}/sbin/mr-jobhistory-daemon.sh --config "${HADOOP_CONF_DIR}" stop historyserver
  RETVAL=$?
  sleep 1
  echo
  [ $RETVAL -eq 0 ] && rm -f /tmp/hadoop-historyserver.lock $PIDFILE
}

restart() {
  stop
  start
}

checkstatus(){
  echo $"$desc $(status -p $PIDFILE)"
  RETVAL=$?
}

condrestart(){
  [ -e /tmp/hadoop-historyserver.lock ] && restart || :
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    checkstatus
    ;;
  restart)
    restart
    ;;
  condrestart)
    condrestart
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|restart|condrestart}"
    exit 1
esac

exit $RETVAL
