#!/bin/bash

source /tmp/hadoop-`echo $USER`/etc/init.d/hadoop.env
source ${HADOOP_HOME}/etc/hadoop/hadoop-env.sh
source ${HADOOP_HOME}/etc/hadoop/yarn-env.sh

RETVAL=0
PIDFILE="${HADOOP_PID_DIR}/hadoop-hdfs-namenode.pid"
desc="Hadoop HDFS NameNode daemon"

start() {
  echo -n $"Starting $desc (hadoop-namenode): "
  ${HADOOP_HOME}/sbin/hadoop-daemon.sh --config "${HADOOP_CONF_DIR}" start namenode
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && touch /tmp/hadoop-namenode.lock
  return $RETVAL
}

upgrade() {
  start -upgrade
}

stop() {
  echo -n $"Stopping $desc (hadoop-namenode): "
  ${HADOOP_HOME}/sbin/hadoop-daemon.sh --config "${HADOOP_CONF_DIR}" stop namenode
  RETVAL=$?
  sleep 1
  echo
  [ $RETVAL -eq 0 ] && rm -f /tmp/hadoop-namenode.lock $PIDFILE
}

checkstatus(){
  echo $"$desc $(status -p $PIDFILE)"
  RETVAL=$?
}

restart() {
  stop
  start
}

condrestart(){
  [ -e /var/lock/subsys/hadoop-namenode ] && restart || :
}

format() {
  daemon --user hdfs ${HADOOP_HOME}/bin/hdfs namenode -format
}

case "$1" in
  start)
    start
    ;;
  upgrade)
    upgrade
    ;;
  format)
    format
    ;;
  stop)
    stop
    ;;
  status)
    checkstatus
    ;;
  restart)
    restart
    ;;
  condrestart|try-restart)
    condrestart
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|restart|try-restart|upgrade}"
    exit 1
esac

exit $RETVAL

