#!/bin/bash

source /tmp/hadoop-`echo $USER`/etc/init.d/hadoop.env
source ${HADOOP_HOME}/etc/hadoop/hadoop-env.sh
source ${HADOOP_HOME}/etc/hadoop/yarn-env.sh

RETVAL=0
PIDFILE="${YARN_PID_DIR}/yarn-yarn-resourcemanager.pid"
desc="Hadoop YARN ResourceManager daemon"

start() {
  echo -n $"Starting $desc (hadoop-yarn-resourcemanager): "
  ${HADOOP_HOME}/sbin/yarn-daemon.sh --config "${HADOOP_CONF_DIR}" start resourcemanager
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && touch /tmp/hadoop-yarn-resourcemanager.lock
  return $RETVAL
}

stop() {
  echo -n $"Stopping $desc (hadoop-yarn-resourcemanager): "
  ${HADOOP_HOME}/sbin/yarn-daemon.sh --config "${HADOOP_CONF_DIR}" stop resourcemanager
  RETVAL=$?
  sleep 1
  echo
  [ $RETVAL -eq 0 ] && rm -f /tmp/hadoop-yarn-resourcemanager.lock $PIDFILE
}

checkstatus(){
  echo $"$desc $(status -p $PIDFILE)"
  RETVAL=$?
}

restart() {
  stop
  start
}

condrestart(){
  [ -e /var/lock/subsys/hadoop-yarn-resourcemanager ] && restart || :
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    checkstatus
    ;;
  restart)
    restart
    ;;
  condrestart|try-restart)
    condrestart
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|restart|try-restart}"
    exit 1
esac

exit $RETVAL
